Reddit/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: :new
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post "downvote"
      post "upvote"
    end
  end
  root to: "subs#index"

end

Reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, :email, :password_digest, :session_token, presence: true
  validates :username, :password_digest, :session_token, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :subs,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Sub

  has_many :posts

  has_many :comments,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Comment

  has_many :votes

  after_initialize :ensure_session_token

  def self.generate_session_token
    begin
      token = SecureRandom::urlsafe_base64
    end while User.exists?(session_token: token)
    token
  end

  def self.find_by_credentials(username,password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  attr_reader :password

  def is_password?(password)
    bc_object = BCrypt::Password.new(self.password_digest)
    bc_object.is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end
end

Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid attributes"]
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

Reddit/app/helpers/users_helper.rb
module UsersHelper
end

Reddit/app/views/users/_form.html.erb
<% action = user.persisted? ? user_url(user) : users_url %>


<form action="<%= action %>" method="post">
  <%= auth_form %>
  <% if user.persisted?  %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <section>
    <label for="email">Email</label>
    <input type="text" name="user[email]" id="email" value="<%= user.email %>">
  </section>

  <section>
    <label for="username">Username</label>
    <input type="text" name="user[username]" id="username" value="<%= user.username %>">
  </section>

  <section>
    <label for="password">Password</label>
    <input type="password" name="user[password]" id="password">
  </section>

  <button>Submit</button>
</form>

Reddit/app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render "form", user: @user %>

Reddit/app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: User.new %>

Reddit/app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<% if current_user.id == @user.id %>
  <%= button_to "Edit", edit_user_url(@user), method: "get" %>
<% end %>