Reddit/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: :new
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post "downvote"
      post "upvote"
    end
  end
  root to: "subs#index"

end

Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  validates :title, :user_id, presence: true
  validates :title, uniqueness: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub

  has_many :posts,
    through: :post_subs,
    source: :post
end

Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :set_sub, only: [:show, :edit, :update, :destroy ]
  before_action :require_self, only: [:edit, :update, :destroy]

  def index
    @subs = Sub.all
  end

  def show
  end

  def new
  end

  def create
    subreddit = Sub.new(sub_params)
    subreddit.moderator = current_user
    if subreddit.save
      redirect_to sub_url(subreddit)
    else
      flash.now[:errors] = subreddit.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
  end

  private

  def set_sub
    @sub = Sub.find(params[:id])
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_self
    if !current_user || (current_user.id != @sub.moderator.id)
      flash.now[:errors] = ["Unauthorized"]
      redirect_to sub_url(@sub)
    end
  end
end

Reddit/app/helpers/subs_helper.rb
module SubsHelper
end

Reddit/app/views/subs/_form.html.erb
<% action = sub.persisted? ? sub_url(sub) : subs_url %>

<form action="<%= action %>" method="post">
  <%= auth_form %>
  <% if sub.persisted?  %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <section>
    <label for="title">Title</label>
    <input type="text" name="sub[title]" id="title" value="<%= sub.title %>">
  </section>

  <section>
    <label for="description">Description</label>
    <input type="text" name="sub[description]" id="description" value="<%= sub.description %>">
  </section>

  <button>Submit</button>
</form>

Reddit/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<%= render "form", sub: @sub %>

Reddit/app/views/subs/index.html.erb
<h1>Subreddits</h1>

<%= button_to "Add SubReddit", new_sub_url, method: "get" %>

<ul class="subs">
  <% @subs.each do |sub| %>
    <li>
      <%= link_to sub.title, sub_url(sub) %>
    </li>
  <% end %>
</ul>

Reddit/app/views/subs/new.html.erb
<h1>New Sub</h1>

<%= render "form", sub: Sub.new %>

Reddit/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<p>
<%= @sub.description %>
</p>

<% if current_user == @sub.moderator %>
  <%= button_to "Edit SubReddit", edit_sub_url(@sub), method: "get" %>
<% end %>

<h2>Posts</h2>

<% @sub.posts.each do |post| %>
  <%= render "posts/post", post: post %>
<% end %>