Reddit/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :subs
  resources :posts do
    resources :comments, only: :new
    member do
      post "downvote"
      post "upvote"
    end
  end
  resources :comments, only: [:create, :show] do
    member do
      post "downvote"
      post "upvote"
    end
  end
  root to: "subs#index"

end

Reddit/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :text
#  content    :text
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  include Commentable
  include Votable
  
  validates :title, :user_id, presence: true
  # validate :has_a_sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub,
    inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub

  def has_a_sub
    if self.subs.empty?
      self.errors[:post] << "must be associated with a sub"
    end
  end
end

Reddit/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :set_subs, only: [:create, :new, :edit]
  before_action :require_login, only: [:new, :create, :edit, :update, :destroy]

  def show
  end

  def new
  end

  def create
    post = Post.new(post_params)
    post.author = current_user
    if post.save
      redirect_to post_url(post)
    else
      # fail
      flash.now[:errors] = post.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def upvote
    vote = Vote.new(author: current_user, value: 1, votable: @post)
    if vote.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to post_url(@post)
    end
  end

  def downvote
    vote = Vote.new(author: current_user, value: -1, votable: @post)
    if vote.save
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to post_url(@post)
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end

  def set_subs
    @subs = Sub.all
  end
end

Reddit/app/helpers/posts_helper.rb
module PostsHelper
end

Reddit/app/views/posts/_form.html.erb
<% action = post.persisted? ? post_url(post) : posts_url %>

<form action="<%= action %>" method="post">
  <%= auth_form %>
  <% if post.persisted?  %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <section>
    <label for="title">Title</label>
    <input type="text" name="post[title]" id="title" value="<%= post.title %>">
  </section>

  <section>
    <label for="url">URL</label>
    <input type="text" name="post[url]" id="url" value="<%= post.url %>">
  </section>

  <section>
    <label for="content">Content</label>
    <input type="content" name="post[content]" id="content">
  </section>

  <section>
    <label>Sub Reddits</label>
    <% @subs.each do |sub| %>
    <label class="checkbox">
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>" <%="checked" if post.sub_ids.include?(sub.id)%> >
    <%= sub.title %>
    </label>
    <% end %>
  </section>

  <button>Submit</button>
</form>

Reddit/app/views/posts/_post.html.erb
<section>
  <%= link_to post.title, post_url(post) %>
  <%= button_to "upvote", upvote_post_url, method: "post" %>
  <%= button_to "downvote", downvote_post_url, method: "post" %>
</section>

Reddit/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render "form", post: @post %>

Reddit/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render "form", post: Post.new %>

Reddit/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<small><%= @post.upvote_count %> upvotes, <%= @post.downvote_count %> downvotes</small>

<p>
  <%= @post.try(:url) %>
</p>

<section class="post-content">
  <h4>Content</h4>
  <p>
    <%= @post.content %>
  </p>
</section>

<section>
  <h4>Comments</h4>
  <ul>
    <% @post.comments.each do |comment| %>
      <%= render "comments/comment", comment: comment %>
    <% end %>
  </ul>
</section>